export default [
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "<__________________>",
];