export default [
    "LSSSSSSSSSSSSSSSSSSR",
    "LSSSSSSSSSSSSSSSSSSR",
    "LSSSSSSSSSSSSSSSSSSR",
    "LSSSSSSSSSSSSSSSSSSR",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "L                  R",
    "<__________________>",
];